"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.usuarioController = void 0;
/**
 * @name
 * @author
 * @creation
 */
class UsuarioController {
    listar(req, res) {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                return res.json("Listar");
            }
            catch (error) {
                console.error(error);
                return res.status(500).json({ mensaje: "Ocurri贸 un error" });
            }
        });
    }
    insertar(req, res) {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                return res.json("Insertar");
            }
            catch (error) {
                console.error(error);
                return res.status(500).json({ mensaje: "Ocurri贸 un error" });
            }
        });
    }
    actualizar(req, res) {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                return res.json("Actualizar");
            }
            catch (error) {
                console.error(error);
                return res.status(500).json({ mensaje: "Ocurri贸 un error" });
            }
        });
    }
    eliminar(req, res) {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                return res.json("Eliminar");
            }
            catch (error) {
                console.error(error);
                return res.status(500).json({ mensaje: "Ocurri贸 un error" });
            }
        });
    }
}
exports.usuarioController = new UsuarioController();
